oracle-samples/oltrain

NBDE/index.html

Example output uses old folder name.

Fix example folder name

---

README.md

Updating copyright to 2020 and adjusting based on new standards from Oracle.
Signed-off-by: Avi Miller <avi.miller@oracle.com>

Updating copyright details.

---

HA-NFS/Vagrantfile
NBDE/Vagrantfile

Resolves #14.
Signed-off-by: Avi Miller <avi.miller@oracle.com>

Updating Vagrantfiles to use box metadata instead of hard-coded URLs.

---

OLCNE-Gluster/index.html
README.md

Signed-off-by: Rafael Benevides <rafael.benevides@oracle.com>

Added references to https://docs.oracle.com/learn/

---

OCNE/ocne.md
OL/intro/intro.md
OLOCI/oloci.md

Added GA and Tech Preview quizzes to OCNE page, and Intro to OL quiz to OL page.

OCNE and OL Intro quizzes added

---

OSMG/osmg.md

Added link and thumbnail to new Linux module streams lab to OSMG page.

Added new module streams lab lab to OSMG page 

---

README.md

Changed link on Whats New graphic from new.md to full https link

Whats new home page link fix

---

OCNE/ocne.md
OL/ol.md
OLAM/olam.md
OLOCI/oloci.md
OLVM/olvm.md
OPCA/opca.md
OSMG/osmg.md
Whats_New/new.md

Dashes not rendered correctly. All pages given same formatting for title and header graphic.

Fixed header spacing issue

---

OL/ol.md

test PR for OL page - MOR

---

OL/ol.md

OL page test reverted - MOR

---

OL/ol.md

OL page test 2 

---

OL/ol.md

Included specific topics covered on each page in descriptions to facilitate keyword searching.

Added additional descriptive text

---

OSMG/osmg.md

Video link corrected on OSMG page.

Update to osmg page

---

OLOCI/oloci.md

Test for inserted link to video on using Luna labs

Test link to Luna video

---

OLOCI/oloci.md

Test2 for for link style for Luna video link.

Test2 for Luna video link

---

OLOCI/oloci.md

Test3 to set Luna video link size and alignment

Test3 for luna video link

---

OLOCI/oloci.md

Test4 for center and style of Luna lab video links on OLOCI page

Test4 Luna link stlye on OLOCI

---

OLOCI/oloci.md

Testing alignment of Luna video thumbnail on OLOCI page.

Test6 OLOCI luna lab link alignment

---

OLOCI/oloci.md

Added center alignment to all Luna video thumbnails on OLOCI page.

Test7 Luna image align on OLOCI

---

OLOCI/oloci.md

Centered all Luna video thumbnails on OLOCI page

Test8 Luna thumbnail alignment

---

OL/virt/virt.md

Anchor links not working on live site, changed link format to full https address.

Anchor link format changed

---

OLOCI/oloci.md

A new header table with anchor links added to OLOCI page. Testing format and layout of header table and anchor links in same page.

New header section and anchor links test1

---

OLOCI/oloci.md

Live page rendering of tags is not even close to preview. Some HTML tag changes to try and fix the image issues.

OLOCI page test format 2

---

OLOCI/oloci.md

Test changes to OLOCI header table causing rendering issue.

OLOCI page foramt test 3

---

OLOCI/oloci.md

Page - OLOCI - removed duplicate graphic, testing vertical alignment in header table - Test 4

OLOCI header table alignment test4

---

OLOCI/oloci.md

OLOCI page - rendering fault from html tag - test5

OLOCI page faulty tag Test5

---

OLOCI/oloci.md

OLOCI page header table fix test 6

OLOCI page test 6

---

OCNE/ocne.md

Added new section for Podman to OCNE page. Created anchor links to containers section (Podman) on OL - virt page.

Podman section added to OCNE

---

OCNE/ocne.md
site_links.txt

Added site_links.txt file for recording anchor and external site links added to site pages.

Added txt file for recording anchor links added to pages

---

README.md

Testing formatting support for new header intro table added to home page.

New home page header table test1

---

README.md

Whats new graphic link centered in the table cell - test2. Typo corrected.

Home page header graphic alignment test2

---

README.md

Modified Whats New graphic link on home page to full http address. Removed line break after header on home page.

Home page whats new link updated

---

OCNE/ocne.md
OLOCI/oloci.md

New intro header table section to OCNE page.

OCNE page header

---

OCNE/ocne.md
OL/admin/admin.md
OL/inst_boot/inst_boot.md
OL/intro/intro.md
OL/ksplice/ksplice.md
OL/mon_log/mon_log.md
OL/network/network.md
OL/ol.md
OL/pkg_mgmt/pkg_mgmt.md
OL/rem_mgmt/rem_mgmt.md
OL/stor_mgmt/stor_mgmt.md
OL/virt/virt.md
OLVM/olvm.md
README.md

Updated multiple anchor links on multiple pages.

Updated anchor links

---

OCNE/ocne.md
OL/virt/virt.md

Testing inter page section anchor links between OCNE and OL pages

ANchor links testing

---

OCNE/ocne.md
OL/virt/virt.md

ONCE anchor link fix

---

OL/ol.md

Added new video keywords to monitoring and logging section.

Update ol.md page

---

OSMH/osmh.md

Fixed horizontal thumbnail layout issue on OSMH page.

OSMH layout fix

---

OSMH/osmh.md
Whats_New/new.md

Updated video changed youtube fix so I updated the video urls to reflect the new link. Thanks!

Youtube link change. Fixed on pages.

---

content/ocne/ocne.md

Remove old content from these sections:
- Kubernetes
- Kata Containers
- Istio

Remove old OCNE video content

---

content/osmh/osmh.md
content/whats-new/new.md

Add the following video to the OSMH page under the Deploying OS Management Hub section and also to the 'What's new' page:
- [Creating Groups in Oracle OS Management Hub](https://youtu.be/4JiabsfKFJ4)

Add new OSMH Creating Groups video

---

config/_default/menus.en.toml

Added the following entries to the OLTrain menu for Verrazzano:
- Verrazzano Documentation site
- Verrazzano Blog site
- Verrazzano YouTube Channel

Add Verrazzano Entries to OLTrain

---

content/vz/vz.md

Correct typo in VZ graphic on main page

Correct typo in VZ graphic on Verrazzano page

---

content/ol/virt/virt.md
content/whats-new/new.md

Add a new Podman Lab ('Run Containers with Podman on Oracle Linux') to the Oracle Linux Virtualization section and also to the "What's New" page.

Add Run Containers with Podman Lab

---

content/ol/virt/virt.md
content/whats-new/new.md

Correcting the Luna Lab URL referenced in PR # 280

Correct Lab URL for mikes latest Podman Lab

---

content/oloci/oloci.md
content/whats-new/new.md

Add new video "_Oracle Secure Desktops Tenancy Setup_" from PM to the 'Oracle Linux on Oracle Cloud Infrastructure' section of OLTrain website

Add video to Linux on Cloud Infrastructure section

---

content/ocne/ocne.md
content/whats-new/new.md

Add a new Oracle Cloud Native Environment Lab to OLTrain:
- [Use ConfigMaps and Secrets with Oracle Cloud Native Environment ](https://luna.oracle.com/lab/14984256-1691-4d7a-8468-6ff38b6253ad)

Add ConfigMaps and Secrets Lab

---

content/osmh/osmh.md
content/whats-new/new.md

Add new video - _Creating Lifecycle Environments in Oracle OS Management Hub_  to OLTrain site

Add new Creating Lifecycle Environments video to OSMH page

---

content/ol/virt/virt.md
content/whats-new/new.md

Add new Podman video to the Virtualization section of the Oracle Linux track:
- _Search Container Registries with Podman on Oracle Linux_

Add new Search containers Podman video to OLTrain

---

content/osd/osd.md
content/whats-new/new.md

Added a new video to the '**Oracle Cloud Infrastructure Secure Desktops**' track and the 'What's new' page:
- _Oracle Cloud Infrastructure Secure Desktops - User's Client View_

Add new video to Oracle Secure Desktops track

---

content/osd/osd.md
content/whats-new/new.md

Added new video to the 'Oracle Secure Desktops' Track and also to the 'Waht's New' page:
- "_Oracle Cloud Infrastructure Secure Desktops - Administration Workflow_"

add new Secure Desktops video

---

content/ol/virt/virt.md
content/whats-new/new.md

Add a new video to the Oracle Linux Virtualization track:
- [_Pull Images with Podman on Oracle Linux_](https://www.youtube.com/watch?v=DFtZYIOPcuU)
and remove an existing (older) video covering the same topic from the Oracle Linux Virtualization track:
- [_Pulling an Image using Podman on Oracle Linux_](https://www.youtube.com/watch?v=QmZE-lFNzk4)

Add Pull Images with Podman video

---

content/osmh/osmh.md
content/whats-new/new.md

Add a new video to the OS Management Hub track:
- [_Managing Jobs in Oracle OS Management Hub_](https://www.youtube.com/watch?v=v4GodjnO1Vo)

Add new video Managing Jobs in Oracle OS Management Hub

---

content/posts/osmh/post-4/index.md

Revise the title to be:
- _Registering On-premises and 3rd Party Cloud Environments with Oracle OS Management Hub_

Update omsh post-4

---

content/posts/oloci/post-28/index.md

Update to OLOCI lab/tutorial post-28:
- Added missing "Lab" tag to meta data.

Update file index.md

---

content/posts/oloci/post-33/index.md
content/posts/oloci/post-34/index.md
content/posts/oloci/post-35/index.md

Archive the following Posts from the OLOCI track:
- Post 33 : Create an Oracle Linux Storage Appliance
- Post 34: Configure Oracle Linux Storage Appliance
- Post 35: Use Oracle Linux Storage Appliance

Remove OLOCI posts - 33, 34, 35

---

content/posts/ol/network/post-6/index.md
content/posts/ol/package/post-1/index.md

Update two videos on the Oracle Linux track:
- Learn how to configure a firewall with firewalld on Oracle Linux.
- Learn how to use DNF on Oracle Linux.

OL/network/post-6 and OL/package/post-1 updated

---

content/posts/ol/virt/post-38/index.md
content/posts/ol/virt/post-39/index.md
content/posts/ol/virt/post-40/index.md
content/posts/ol/virt/post-43/index.md
content/posts/ol/virt/post-44/index.md
content/posts/ol/virt/post-45/index.md
content/posts/ol/virt/post-46/index.md
content/posts/ol/virt/post-47/index.md

Update the following videos in the Oracle Linux/Vitualization track:
- Stop Containers
- Remove Containers
- Remove Container Images
- Create Containers
- Run Containers
- Search Container Registries
- Pull Container Images
- Build Custom Images

Updated ol/virt/post-38,39,40,43,44,45,46,47

---

content/posts/ol/intro/post-6/index.md

Updated video in the Oracle Linux/Intro/ track:
- "Learn how work with users and groups on Oracle Linux."

Updated post ol/intro/post-6 - "Learn how work with users and groups on Oracle Linux."
